services:
  - type: web
    name: gmgn-crawler
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web_app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: false